### ISSUE TITLE
Port HTML parser

### ISSUE THREAD

**Issue by mdittmer** [GoogleChrome/webidl-diff#3]
This will eliminate need for a heavy third-party dependency. There exists a pretty good one against FOAM1 APIs. We should make sure a FOAM2 implementation facilitates our use case:

`querySelectorAll('pre.idl').concat(querySelectorAll('xmp.idl')).map(e => e.textContent)`

**Comment by mdittmer** [comment]
... in particular, `xmp` doesn't interpret markup inside it. E.g., `<xmp>Promise<void></xmp>` has a `.textContent` value of `Promise<void>`.

**Comment by mdittmer** [comment]
Lexer implemented in https://github.com/foam-framework/foam2/pull/267

**Comment by m-cheung** [comment]
Is this considered resolved by foam-framework/foam2#267 (and the other changes I made to the FOAM HTML Lexer) + #46?
