### ISSUE TITLE
Unable to parse certain Namespaces and constant declarations

### ISSUE THREAD

**Issue by m-cheung** [GoogleChrome/webidl-diff#48]
1. The following snippet, found in one of the [IDL files in the Mozilla Gecko repo](https://github.com/mozilla/gecko/blob/central/dom/webidl/Console.webidl), does not currently parse
```
namespace console {
  *irrelevant content*
  void profileEnd(any... data);
  
  [ChromeOnly]
  const boolean IS_NATIVE_CONSOLE = true;
}
```

2. Additionally, found in one of the [IDL files in WebKit repo](https://github.com/WebKit/webkit/blob/master/Source/WebCore/html/canvas/WebGPURenderingContext.idl), also fails to parse
```
interface WebGPURenderingContext {
  const unsigned int PixelFormatBGRA8Unorm = 80;
  *...*
};
```

3. Extended attributes with parameters but no type can be found in many WebKit IDL, fails to parse as well.
```
[   
    object,
    oleautomation,
    hidden,
    uuid(C6F9232A-1E7D-4614-BDAE-150262DE6884),
    pointer_default(unique)
]

interface IAccessibilityDelegate : IUnknown
{
    HRESULT fireFrameLoadStartedEvents();
    HRESULT fireFrameLoadFinishedEvents();
} 
```

4. Pointer-like definitions appear in WebKit IDLs as well. These also fail to parse... Snippet taking from [AccessibleApplication.idl](https://github.com/WebKit/webkit/blob/master/Source/WebKit/win/Interfaces/Accessible2/AccessibleApplication.idl)
```
[object, uuid(D49DED83-5B25-43F4-9B95-93B44595979E)]
interface IAccessibleApplication : IUnknown
{
  *...*
  [propget] HRESULT appName
    (
     [out, retval] BSTR *name
    );
 *...*
}
```

Found while attempting to resolve #39

**Comment by m-cheung** [comment]
1. This bug is unrelated to this [workaround](https://github.com/GoogleChrome/webidl-diff/blob/master/lib/org/chromium/webidl/Parser.js#L189).
**Cause**: The parser is not consuming spaces between `NamespaceMember`
**Solution**: Changing grammar to account for that. Will be coming as part of the PR to resolve #39 

2. This bug is seems to be partially related to this [workaround](https://github.com/GoogleChrome/webidl-diff/blob/master/lib/org/chromium/webidl/Parser.js#L375). 
**Cause**: The grammar does not recognize the pattern `unsigned int` (`int` is not a built in type). There does not seem to be a rule for recognizing unsigned custom types in [HeyCam's IDL spec](https://heycam.github.io/webidl/). Perhaps the author of the IDL file meant `const unsigned long ...`?
**Solution**: Temporarily added `int` to list of `BuiltInType`

3. Resolved by adding an additional semantic rule specific to WebKit. Note that many IDL Interface definitions have no semicolon, and the semantic rule for that had to be relaxed as well...

4. The WebIDL specification for identifiers do not allow for `*` within identifiers. We will likely have add an additional semantic rule for WebKit's parser to handle this
-> These exceptions were found outside of the `Source/WebCore` directory and they will now be ignored.

**Comment by m-cheung** [comment]
3. Resolved by adding an additional semantic rule specific to WebKit. Note that many IDL Interface definitions have no semicolon, and the semantic rule for that had to be relaxed as well...

**Comment by mdittmer** [comment]
This is now fixed, yes?

**Comment by m-cheung** [comment]
Yes, it has been fixed. Closing now
